# Generated by Django 2.2.4 on 2019-08-23 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sso_server', '0003_consumer_perm_sync_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsumerpermissions',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sso_server.Consumer', verbose_name='Consumer'),
        ),
        migrations.AlterField(
            model_name='userconsumerpermissions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
