# Generated by Django 2.2.4 on 2019-08-23 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sso_server', '0004_auto_20190823_0740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserConsumerPermissions',
            new_name='UserConsumerPermission',
        ),
        migrations.AlterModelOptions(
            name='userconsumerpermission',
            options={'verbose_name': 'UserConsumerPermission', 'verbose_name_plural': 'UserConsumerPermissions'},
        ),
        migrations.AlterUniqueTogether(
            name='userconsumerpermission',
            unique_together={('consumer', 'user')},
        ),
    ]
